# SPDX-License-Identifier: GPL-2.0
#
# Generic Hardware Spinlock framework
#

obj-$(CONFIG_HWSPINLOCK)		+= hwspinlock_core.o
obj-$(CONFIG_HWSPINLOCK_OMAP)		+= omap_hwspinlock.o
obj-$(CONFIG_HWSPINLOCK_QCOM)		+= qcom_hwspinlock.o
obj-$(CONFIG_HWSPINLOCK_SIRF)		+= sirf_hwspinlock.o
obj-$(CONFIG_HWSPINLOCK_SPRD)		+= sprd_hwspinlock.o
obj-$(CONFIG_HWSPINLOCK_STM32)		+= stm32_hwspinlock.o
obj-$(CONFIG_HSEM_U8500)		+= u8500_hsem.o
obj-$(CONFIG_HWSEM_MA35D1)		+= ma35d1_hwsem.o
obj-$(CONFIG_HWSEM_MA35D0)		+= ma35d0_hwsem.o
obj-$(CONFIG_HWSEM_MA35H0)		+= ma35h0_hwsem.o
