#
# Makefile for mmp specific clk
#
obj-$(CONFIG_ARCH_MA35D1) += clk-ma35d1.o clkdivider-ma35d1.o clk-ma35d1-pll.o
obj-$(CONFIG_ARCH_MA35D0) += clk-ma35d0.o clkdivider-ma35d0.o clk-ma35d0-pll.o
obj-$(CONFIG_ARCH_MA35H0) += clk-ma35h0.o clkdivider-ma35h0.o clk-ma35h0-pll.o



