# SPDX-License-Identifier: GPL-2.0
# MA35D1 series audio

snd-soc-ma35d1-pcm-objs := ma35d1-pcm.o
snd-soc-ma35d1-i2s-objs := ma35d1-i2s.o

obj-$(CONFIG_SND_SOC_MA35D1) += snd-soc-ma35d1-i2s.o snd-soc-ma35d1-pcm.o
# obj-$(CONFIG_SND_SOC_MA35D1) += snd-soc-ma35d1-i2s.o

# Boards
snd-soc-ma35d1-audio-objs := ma35d1-audio.o

obj-$(CONFIG_SND_SOC_MA35D1EVB) += snd-soc-ma35d1-audio.o
