# SPDX-License-Identifier: GPL-2.0
# MA35D0 series audio

snd-soc-ma35d0-pcm-objs := ma35d0-pcm.o
snd-soc-ma35d0-i2s-objs := ma35d0-i2s.o

obj-$(CONFIG_SND_SOC_MA35D0) += snd-soc-ma35d0-i2s.o snd-soc-ma35d0-pcm.o
# obj-$(CONFIG_SND_SOC_MA35D0) += snd-soc-ma35d0-i2s.o

# Boards
snd-soc-ma35d0-audio-objs := ma35d0-audio.o

obj-$(CONFIG_SND_SOC_MA35D0EVB) += snd-soc-ma35d0-audio.o
