# SPDX-License-Identifier: GPL-2.0
# MA35H0 series audio

snd-soc-ma35h0-pcm-objs := ma35h0-pcm.o
snd-soc-ma35h0-i2s-objs := ma35h0-i2s.o

obj-$(CONFIG_SND_SOC_MA35H0) += snd-soc-ma35h0-i2s.o snd-soc-ma35h0-pcm.o
# obj-$(CONFIG_SND_SOC_MA35H0) += snd-soc-ma35h0-i2s.o

# Boards
snd-soc-ma35h0-audio-objs := ma35h0-audio.o

obj-$(CONFIG_SND_SOC_MA35H0EVB) += snd-soc-ma35h0-audio.o
